server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/ratings
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, beans, info, metrics, env, configprops, auditevents, httptrace, threaddump, loggers